### ISSUE TITLE
"Blaze child events" proxy-ing event handlers to React component children.

### ISSUE THREAD

**Issue by timbrandin** [timbrandin/blaze-react#28]
Regarding passing down events to children from Phase 2, I found this:
http://www.bennadel.com/blog/2916-attaching-dynamic-event-handlers-to-proxied-child-elements-in-reactjs.htm (check the video around 5:30)

Basically what they are doing is cloning the element and passing down event handlers, though I'm not sure how Blaze passes down the event handlers. I suspect they get attached to the matching DOM element in the Template, that could get tricky!

**Comment by timbrandin** [comment]
Something like this:
```
// I return the virtual DOM represented by the current component state.
            render: function() {

                // When we render the "directive component", we're really just rendering
                // the child element as there is no additional markup to render. However,
                // since we are adding dynamic behavior, we need to clone the the child
                // in order to mix-in the props for mouse-interaction.
                // --
                // NOTE: Since we are using "props" to bind mouse-event handlers, we know
                // that ReactJS is going to bind them using event delegation. This means
                // that we do NOT HAVE TO WORRY about the element unmounting or event
                // changing. Heck, it means we don't even have to unbind event handlers
                // when we want to change them - we simply define a new set of handlers.
                var props = _.extend(
                    {
                        ref: this.handleRefChange
                    },
                    this.state.handlers
                );

                return( React.cloneElement( this.props.children, props ) );

            },
```

**Comment by timbrandin** [comment]
We could also do something like this:
https://facebook.github.io/react/tips/dom-event-listeners.html

**Comment by faceyspacey** [comment]
I think one side goal we should have is generating code that looks as much like what you would actually write yourself as possible. That way eventually developers can just switch over to the React version of their code completely with ease. 

...in your example: 
`return( React.cloneElement( this.props.children, props ) );`
do we really have to clone an element. Why can't we just use spread attributes that contains all the handlers we wanna pass down: 
```
<Component {...handlers}>
```
..What I was thinking was we just pass them down till the handler matches an element, and then we assign it at that point. ..I guess that won't work for all selectors, since you could have something like: `body table tr td` and the `td` is nested several components from the `body` and therefore its selector won't match. That said, that's rare in Meteor. Since selectors are already scoped to a parent template, they usually have pretty simple selectors. 

Dom listeners definitely would work, but if we can find a more "react way" to do it, we should. Basically the first way we're talking about is it if we can guarantee the matchup of handlers to all elements they are supposed to select.

**Comment by faceyspacey** [comment]
i dont think `window.addEventListener` is even an option since the whole point of what we're doing is basically to achieve Blaze Native. That's what will make this all truly worth it. Sure, there is a lot of other packages in the React ecosystem we will get to, but none more important than that one. So unless `window.addEventListener` is shimmed for React Native, it's a no go.

**Comment by timbrandin** [comment]
It would be really great for us if we didn't have to worry about event selectors working on child components, it would be so much better to avoid it.

Yep, you are right, we don't need to clone the element, unless doing so would enable us to attach events to it's children.

**Comment by faceyspacey** [comment]
well we build it in stage 1 without attaching events to children. lets barely think about it. this will allow us to build with a consistent architecture shared between helpers and events (they are exactly the same in terms of data context). So even if we have to do something more unique for Events, its not like Helpers didnt need the same solution. After this is all working, we'll have a better view of more feature-complete options. 

Check out what I wrote here for a more holistic strategy:

https://github.com/timbrandin/react-templates/pull/1/files#r44759084

If ur down to do that, i can break it into a more organized checklist rather than a stream of thought post.

**Comment by faceyspacey** [comment]
....thought about this more. here's the most comprehensive solution yet:

 - we dynamically pre-render what will be returned from `render`, then we see what elements have what classes/ids/etc at that time, then go back to the original js that generated it and attach the handlers via regex (that is if we can't just attach it to "markup" somehow after its generated, which is doubtful given its not real markup). Then we return the eval of that new code. Keep in mind, Blaze 1.0 Renderer is a stop gap--as long as it works is all that matters in the migration path forward; Blaze 1.0-based components will be used less and less in projects, and the code that causes this performance hit doesn't have to be used on true components. 
 - as for event selectors being able to take into consideration the parent portion of their css, we need to make accessible the equivalent of a `$`-scoped object to each rendered component, and somehow use that to scope the css selector, just as `template.$()` does so in Blaze. This is more of a general idea. Its implementation is far from clear, but if we can somehow get DOM scope for each component, we are in the money. Even if it's fake, i.e. virtual dom, it will work. 

As usual, I refuse to believe anything is not possible unless every avenue has been fully and truly explored. A lot of these ideas are "hacks" that will take hits on performance, but I'm fine with that, given the goal, *and there is a future for the components-based "Blaze" interface regardless.* We just need to make the path forward to that as seamless as possible. I dont want to use Blaze 1.0. I want to use Blaze 2.0--just while not losing support for legacy Blaze 1.0 code. I can optimize performance gradually over time as more and more packages begin to go pure "Blaze 2.0". That's the thinking I'd like to advocate here.

**Comment by faceyspacey** [comment]
another caveat is that React Context is all set statically:

```
var MessageList = React.createClass({
  childContextTypes: {
    color: React.PropTypes.string
  },
  getChildContext: function() {
    return {color: "purple"};
  },
  render: function() {
    var children = this.props.messages.map(function(message) {
      return <Message text={message.text} />;
    });
    return <div>{children}</div>;
  }
});
```

We likely can find a way to do that dynamically as each render tree is composed. However, it just be better to have a dedicated prop key such as `__eventsMap` which we pass down from component to component. React Contexts were a nice idea, but with all the rules required to check `contextTypes` may require more work than its worth. So in short, the improved strategy is:

1. in each component's render method, discover all event handlers (they will be tacked on the component with the same names as in their Blaze event maps, eg: 'click .some element'). So we treat methods named as such as event handlers. In the render method at render time, we get that list (though we can cache it since they are expected to be statically defined).
2. we pass down a map of all those methods to all child components in `this.props.__eventsMap`
3. in all child components (well parent/owner components as well), we match up event handlers to the elements they select (and of course the event type attributes). THIS IS THE HARD PART WE STILL NEED TO FIGURE OUT.
4. the correct component context for the event handler to run in is set when we discover it. So we dont need to do any work here. Since we collect all handlers dynamically at the render time of each component, we can also quickly do this: `eventHandler = eventHandler.bind(this)`.

Our `BlazeReact` mixin will define a method called  `this.getEventHandlers` which we can use. It will look something like this:

```
getEventHandlers() {
       return _.chain(this.getPrototype()) //method we make that gives instances access to their prototype
           .mapObject((handler, name) => { //transform values of object keys
              return name ? this._isEventHandler(name) : undefined;
           }, this)
           .clean().value(); //remove undefined properties
}
_isEventHandler(name) {
      return /^(click|focus|etc)(\s|$)/.test(name) && _.isFunction(name);
}
```

**Comment by faceyspacey** [comment]
there's what seems like the final complication: 

when you pass these event handlers down like so, having bound them to the parent instance context, you lose the value of `this.props`. Perhaps that is the one too automagical thing that Blaze ever did. And if we did settle on the one limitation being that event handlers, that would be it. Though in my Blaze Components spec, in combination with helpers operating the same way, does make a fantastic way to manage state from parent components. But without that is quite rediculous. So in plain Blaze 1.0 it would make a decent documented limitation since it doesn't get you much since you can't use it to access state that helpers have anyway. 

But that all said, provided we can solve the above issue with determining dynamic selectors from parent to child components, we'd have to revert back to a permutation of this plan based on an earlier idea: binding the component context in the component that uses it by traversing back up the component tree to the parent that implemented. We'd do that because before we bind that context, we would replace it's value for `this.props` with that of the child component's `this.props`. 

Now replacing it on the parent component instance would of course overwrite the parent's value for `this.props` which would be majorly breaking of the whole system. So we would have to reliably clone the parent instance, essentially instantiating a new one with all the same properties. Now that would be the first thing that would risk being way too heavy performance wise. But there may be another option: we have to consider that we are the ones generating this React code. So we were gonna generate `this.props('key')` (currently called `this.lookup()`) as functions anyway, which under the hood does various binding. In that function we give ourselves access to the child component and can then use its value for `props` instead of that of the parent component where the event handler is defined.

**Comment by faceyspacey** [comment]
...and it's totally possible and super easy to render the entire tree, collecting element selectors to determine which events to attach events to:

http://jsfiddle.net/yv8vnhLh/

go to line 47, then open up the console and click INCREMENT ALL. You will see I start practicing rendering the entire tree starting from a parent component, then this current component, and then a dynamic render method as well. 

So basically we can generate all this HTML in `componentWillUpdate` or similar and then parse it, inject event handler attributes, and then return the eval of that string in the render method instead of the pre-event-handlers-attached render template. Hopefully while being evaled, it doesn't bypass the JSX interpreter. Perhaps we might need to generate the javascript version of the string, but that wouldn't be that hard either. And then if we have to we can call `component.forceUpdate` to utilize our render return instead of the pre-event-handlers-attached one.

It's a lot of steps, and probably heavier than everything else the app would naturally do, but it works. Again, it's a stop gap. Eventually old blaze code will be replaced. 

So basically it's all possible:

 - we can accumulate event handlers down the tree, then call them with the correct context and value for this
 - we can bind helper props like you already built
 - we can sideways load data so that cursors can be used in methods/helpers without the need for `getMeteorData`--again via `forceUpdate`
 - we can make `Template.parentData(level)` and `../../` in spacebars work by passing down a reference to a component's parent on rendering.

**Comment by faceyspacey** [comment]
what should be done in fact is a "Meteor React" package. Basically a version similar to what Meteor made with `getMeteorData` but where we mirror the Blaze style of context. I.e. just to prove that these pitfalls are not in fact pitfalls. That will be quicker to make, and be what @yyx990803 @gschmidt should look at to see what is in fact possible here. 

So the defining thing for what this would look like is event handlers defined on parent templates like this:

```
class ParentComponent extends React.Component {
   ['click .some-class']: function() {}
}
```

and then have an example where a child component is clicked that triggers that handler, after of course the system under the hood automatically determines what child component elements to attach it to, while binding the correct parent component as the context for `this` and setting the value for props to the child element like how event selectors work in Blaze. The one caveat is we may have to make `this.props` be `this.props()` instead. But that's planned anyway for fine-grained reactivity on `props` and `state` anyway. And under the hood it eventually calls `this.props`.

**Comment by faceyspacey** [comment]
DONE: https://forums.meteor.com/t/rendering-blaze-1-to-react-is-looking-100-possible/13666?u=faceyspacey

**Comment by faceyspacey** [comment]
here is dynamic event attachment from selectors at render time:

http://jsfiddle.net/morwkzgg/

that the final challenge on my plate.

**Comment by timbrandin** [comment]
Events are passed down to children as expected in Blaze.
