### ISSUE TITLE
Is sideburn having the issue like blaze had?

### ISSUE THREAD

**Issue by txs** [timbrandin/blaze-react#34]
Blaze will rerender the top down passing parameters if the props and states change. So kadira have a project called blaze-plus. Does this happen to sideburn? https://github.com/kadirahq/blaze-plus

**Comment by faceyspacey** [comment]
the goal of sideburns, now called "Blaze React" is to re-render Blaze exactly as it is perfectly. Not Blaze plus. so if/when all goes well, the answer will be NO unless it's how regular Blaze behaves.

**Comment by txs** [comment]
So that means the template will rerender or just translate to react  states
way?

**Comment by faceyspacey** [comment]
I gotta do some more tests to see if we get those benefits from React. 

There is one problem though: Blaze code that thinks the template will re-render and uses the `onRendered` callback to perform an animation. So we may be able to naturally get the less re-rendering benefits of React(similar to Blaze Plus), but then animations and other work developers put in `onRendered` callbacks won't be triggered. If we are trying to offering the ability to switch out the renderer without changes to the application, this wont work. However, if we are trying to essentially make a better version of Blaze and we are ok with asking developers to make a few changes, this will be fine. 

One solution could be a developer-provided flag that lets the developer choose how the Blaze-React renderer behaves. 

We currently aren't at the point in development of this package where we are ready to make this decision. We still have many more core use cases to address. We'll keep this in mind when we get to it. We really are trying to achieve the goal where you can just switch out the renderer and your application keeps working, but at the same time, we are trying to move developers to better patterns of developers, i.e. more performant ones, more easily testable unidirectional immutable ones. 

So if it comes down to various configuration flags you can set to configure the behavior of Blaze React, I wouldn't be opposed. 

We also are going to have a version that transpiles your code once (i.e. not in a build step) so that you can start working with your React code directly. This may be the better place to make such optimizations. 

Now that all said, we will have to figure if there is anything we an do to control this rendering behavior--it might just be out of our hands once the code is transpiled to React; and that's a bigger problem--because then you can't just switch out your renderer and have your code render just as it did with Blaze. The code might not even work. So I'm more concerned with making your Blaze code operate fully as is (with a React renderer) first.

**Comment by txs** [comment]
Thanks  Tim.  I can help if the content block is built.  Thanks
