### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by s7dhansh** [timbrandin/blaze-react#48]
There has not been any pulse in the last few months. The Readme says though that it is in constant development, and a preview release is on the way. What is the actual status then? @timbrandin, can you please help us.

**Comment by timbrandin** [comment]
Yeah, seams like everyone is moving to pure React anyhow, and Blaze works really well inside React so you can port your app one template at the time instead which is actually really good, because constant refactoring is great! So this project might just end up going away, but for now use as you like or learn by from all the amazing regex's there are in here. :)

**Comment by s7dhansh** [comment]
Hmm.. ok. Still, I will miss the Blazeasiness :(

**Comment by timbrandin** [comment]
You should have a look at stateless components, it's actually less code
than a template but you can do much much more. I really like the
flexibility of React with all that, I know it's a mental transition to get
over that easyness, but you'll soon feel as comfortable with React as you
are with Blaze. :)

**Comment by s7dhansh** [comment]
Yes.. I am slowly learning the tricks. When you say Blaze inside React, do you mean something like this? http://stackoverflow.com/a/36271571

**Comment by timbrandin** [comment]
No, more like this: https://guide.meteor.com/react.html#blaze-in-react

**Comment by s7dhansh** [comment]
Oh that is awesome. I somehow missed this when I read the guide a couple of weeks ago.
